import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

/**
 * Export standings as an official EBF PDF document.
 * @param {Array}  standings  - Sorted standings array from calculateStandings()
 * @param {Object} options    - { roundLabel, gender, seasonYear }
 */
export async function exportStandingsPdf(standings, options = {}) {
  const { roundLabel = 'Round', gender = '', seasonYear = '' } = options

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // ─── Header ─────────────────────────────────────────────────────────────
  doc.setFillColor(13, 27, 42)    // navy-900
  doc.rect(0, 0, 210, 40, 'F')

  doc.setTextColor(232, 87, 26)   // ebf-orange
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('EBF LEAGUE MANAGEMENT', 105, 16, { align: 'center' })

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.text(`Ethiopian Basketball Federation — Official Standings`, 105, 24, { align: 'center' })

  doc.setTextColor(200, 200, 200)
  doc.setFontSize(10)
  doc.text(`${gender} Division  |  ${roundLabel}  |  Season ${seasonYear}`, 105, 31, { align: 'center' })

  // ─── Table ───────────────────────────────────────────────────────────────
  const rows = standings.map(s => [
    s.rank,
    s.team.name,
    s.played,
    s.wins,
    s.losses,
    s.ptsDiff > 0 ? `+${s.ptsDiff}` : s.ptsDiff,
    s.leaguePts,
  ])

  autoTable(doc, {
    startY: 46,
    head: [['#', 'Team', 'P', 'W', 'L', 'PD', 'Pts']],
    body: rows,
    headStyles: {
      fillColor: [232, 87, 26],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
    },
    bodyStyles: {
      fillColor: [17, 34, 54],
      textColor: [220, 220, 220],
      halign: 'center',
    },
    alternateRowStyles: {
      fillColor: [13, 27, 42],
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 12 },
      1: { halign: 'left', cellWidth: 80 },
      2: { cellWidth: 15 },
      3: { cellWidth: 15 },
      4: { cellWidth: 15 },
      5: { cellWidth: 20 },
      6: { cellWidth: 20, fontStyle: 'bold', textColor: [232, 87, 26] },
    },
    didDrawRow: (data) => {
      // Highlight top 2 rows with gold accent
      if (data.row.index === 0) {
        doc.setFillColor(245, 166, 35, 0.2)
      }
    },
  })

  // ─── Footer ──────────────────────────────────────────────────────────────
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(8)
  doc.setTextColor(120, 120, 120)
  doc.text(
    `Generated by EBF League Management System · ${new Date().toLocaleDateString('en-GB')}`,
    105, pageHeight - 10, { align: 'center' }
  )

  doc.save(`EBF_Standings_${roundLabel.replace(/\s+/g, '_')}_${seasonYear}.pdf`)
}
